export interface  Dependent {
    idDep: number;
    lienDis: number ;
    lienMast: number;
    prenom: string;
    nom: string;
    datenais: string;
    depTyp: number;
    actif: boolean;
    deleted: boolean;
    lienBanque: number;
    regio: number;
    civilite: number;
    civilitelabel: string; // calculated Property
    eq: number;
    totalRecords: number;
}
export function compareDependents(c1: Dependent, c2: Dependent) {

    const compare = c1.idDep > c2.idDep;

    if (compare) {
        return 1;
    } else if ( c1.idDep < c2.idDep) {
        return -1;
    } else { return 0; }

}

export class DefaultDependent implements Dependent {
    actif: boolean;
    civilite: number;
    civilitelabel: string; // calculated Property
    datenais: string;
    deleted: boolean;
    depTyp: number;
    eq: number;
    idDep: number;
    lienBanque: number;
    lienDis: number;
    lienMast: number;
    nom: string;
    prenom: string;
    regio: number;
    totalRecords: number;


    constructor() {
        this.actif = true;
        this.civilite = 1;
        this.civilitelabel = 'Mr.';
        this.datenais = '';
        this.deleted = false;
        this.depTyp = 1;
        this.eq = 1;
        // this.idDep no Id in default constructor for new Dependent, will be autogenerated
        this.lienBanque = 0;
        this.lienDis = 0;
        this.lienMast = 0;
        this.nom = '';
        this.prenom = '';
        this.regio = 0;
        this.totalRecords = 1;
    }
}
