export interface  Banque {

 bankId: number;

 bankShortName: string;

 bankName: string;

 nrEntr: string;

 bankMail: string;

 actif: number;

 comGest: number;

 lastvisit: string;

 idMemberPres: number;

 idMemberVp: number;

 idMemberSec: number;

 idMemberTres: number;

 idMemberIt: number;

 idMemberLog: number;

 idMemberRh: number;

 idMemberSh: number;

 idMemberPp: number;

 idMemberAsso: number;

 idMemberAppro: number;

 idMemberPubrel: number;

 idMemberCeo: number;

 idMemberFead: number;

 idMemberQual: number;

 adresse: string;

 cp: string;

 localite: string;

 bankTel: string;

 bankGsm: string;

 adresseDepotPrinc: string;

 cpDepotPrinc: string;

 cityDepotPrinc: string;

 depPrincTel: string;

 ssAdresse: string;

 ssCp: string;

 ssCity: string;

 ssTel: string;

 regio: number;

 website: string;

 bank: string;
}

export function compareBanques(c1: Banque, c2: Banque) {

 const compare = c1.bankId - c2.bankId;

 if (compare > 0) {
  return 1;
 } else if ( compare < 0) {
  return -1;
 } else { return 0; }

}
export class DefaultBanque implements Banque {
   actif: number;
   adresse: string;
   adresseDepotPrinc: string;
   bank: string;
   bankGsm: string;
   bankId: number;
   bankMail: string;
   bankName: string;
   bankShortName: string;
   bankTel: string;
   cityDepotPrinc: string;
   comGest: number;
   cp: string;
   cpDepotPrinc: string;
   depPrincTel: string;
   idMemberAppro: number;
   idMemberAsso: number;
   idMemberCeo: number;
   idMemberFead: number;
   idMemberIt: number;
   idMemberLog: number;
   idMemberPp: number;
   idMemberPres: number;
   idMemberPubrel: number;
   idMemberQual: number;
   idMemberRh: number;
   idMemberSec: number;
   idMemberSh: number;
   idMemberTres: number;
   idMemberVp: number;
   lastvisit: string;
   localite: string;
   nrEntr: string;
   regio: number;
   ssAdresse: string;
   ssCity: string;
   ssCp: string;
   ssTel: string;
   website: string;
 constructor() {
  this.actif = 0;
  this.adresse = '';
  this.adresseDepotPrinc = '';
  this.bank = '';
  this.bankGsm = '';
  // this.bankId = 0; omit in constructor will be autogenerated when creating a new banque
  this.bankMail = '';
  this.bankName = '';
  this.bankShortName = '';
  this.bankTel = '';
  this.cityDepotPrinc = '';
  this.comGest = 0;
  this.cp = '';
  this.cpDepotPrinc = '';
  this.depPrincTel = '';
  this.idMemberAppro = 0;
  this.idMemberAsso = 0;
  this.idMemberCeo = 0;
  this.idMemberFead = 0;
  this.idMemberIt = 0;
  this.idMemberLog = 0;
  this.idMemberPp = 0;
  this.idMemberPres = 0;
  this.idMemberPubrel = 0;
  this.idMemberQual = 0;
  this.idMemberRh = 0;
  this.idMemberSec = 0;
  this.idMemberSh = 0;
  this.idMemberTres = 0;
  this.idMemberVp = 0;
  this.lastvisit = '';
  this.localite = '';
  this.nrEntr = '';
  this.regio = 0;
  this.ssAdresse = '';
  this.ssCity = '';
  this.ssCp = '';
  this.ssTel = '';
  this.website = '';
 }
}
